# Generated by Django 2.0.3 on 2018-05-28 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='songCommit',
            fields=[
                ('commit_id', models.AutoField(primary_key=True, serialize=False)),
                ('commit_details', models.CharField(max_length=255)),
                ('commit_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['commit_date'],
            },
        ),
        migrations.CreateModel(
            name='songLikes',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('like_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-like_date'],
            },
        ),
        migrations.CreateModel(
            name='songShare',
            fields=[
                ('share_id', models.AutoField(primary_key=True, serialize=False)),
                ('share_commit', models.CharField(max_length=255)),
                ('share_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-share_date'],
            },
        ),
        migrations.CreateModel(
            name='songsInf',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=40)),
                ('song_author', models.CharField(max_length=40)),
                ('song_url', models.CharField(max_length=255)),
                ('song_lyric', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='userInf',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_nickname', models.CharField(max_length=30)),
                ('user_passwd', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='songshare',
            name='share_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_from_user', to='serviceApp.userInf'),
        ),
        migrations.AddField(
            model_name='songshare',
            name='share_song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_song', to='serviceApp.songsInf'),
        ),
        migrations.AddField(
            model_name='songshare',
            name='share_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_to_user', to='serviceApp.userInf'),
        ),
        migrations.AddField(
            model_name='songlikes',
            name='like_song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_song', to='serviceApp.songsInf'),
        ),
        migrations.AddField(
            model_name='songlikes',
            name='like_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='serviceApp.userInf'),
        ),
        migrations.AddField(
            model_name='songcommit',
            name='commit_song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit_song', to='serviceApp.songsInf'),
        ),
        migrations.AddField(
            model_name='songcommit',
            name='commit_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit_user', to='serviceApp.userInf'),
        ),
    ]
